# Generated by Django 3.0.3 on 2020-05-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200508_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='yoc',
        ),
    ]
