# Generated by Django 3.0.3 on 2020-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200508_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=50)),
                ('holiday_date', models.DateTimeField(null=True)),
                ('holiday_description', models.CharField(max_length=100)),
            ],
        ),
    ]
