# Generated by Django 3.0.5 on 2020-05-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_user_userrole_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField()),
                ('create', models.BooleanField()),
                ('edit', models.BooleanField()),
                ('delete', models.BooleanField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.MenuMaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.UserRole')),
            ],
        ),
    ]
