# Generated by Django 3.0.6 on 2020-05-31 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200521_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 31, 11, 14, 52, 672576))),
                ('attendance_checkin', models.CharField(default='9.00', max_length=100)),
                ('attendance_checkout', models.CharField(default='5.00', max_length=100)),
                ('attendance_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Employee')),
            ],
        ),
    ]
