# Generated by Django 3.0.3 on 2020-06-01 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 1, 11, 48, 2, 938550)),
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.IntegerField()),
                ('da', models.IntegerField()),
                ('ta', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('ma', models.IntegerField()),
                ('pf', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('e_total', models.IntegerField()),
                ('d_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Designation')),
            ],
        ),
    ]
