# Generated by Django 3.0.3 on 2020-06-10 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200610_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 17, 10, 7, 260)),
        ),
    ]
