# Generated by Django 3.0.3 on 2020-06-10 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200610_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='totalhand',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 10, 17, 58, 56, 310115)),
        ),
    ]
