# Generated by Django 3.0.3 on 2020-06-11 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200610_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 11, 19, 19, 58, 467492)),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100)),
                ('leave_from_date', models.DateTimeField(null=True)),
                ('leave_to_date', models.DateTimeField(null=True)),
                ('leave_msg', models.CharField(max_length=100)),
                ('leave_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Employee')),
                ('leave_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Leave_status')),
            ],
        ),
    ]
